### ISSUE TITLE
Mobile nav is broken on android

### ISSUE THREAD

**Issue by Vijar** [yahoo/fluxible.io#111]
Using Chrome on Galaxy S4 this is what I see:
![image](https://cloud.githubusercontent.com/assets/759766/6855361/a75aaa4e-d3b4-11e4-9388-1449585de9d0.png)

**Comment by redonkulus** [comment]
I fixed: https://github.com/yahoo/fluxible.io/commit/bfddf66d830a61c558b7c5aff86956ccf8205814
