### ISSUE TITLE
Dynamic routes (routes.js file)

### ISSUE THREAD

**Issue by daannijkamp** [yahoo/fluxible.io#115]
Is it not possible to have dynamic routes (routes.js file)?

Now all the routes are hard coded in the routes.js file. If there is some new documentation, the routes.js file also needs to change. 
It would be great if it was possible to generate (the functionality of) routes.js automatically based on the markdown files / folder structure of the docs.

I have only no idea how to do this (in a sensible way).

**Comment by redonkulus** [comment]
@daannijkamp not currently, but we have a larger refactor in the work that will allow dynamic routing via the new fluxible-router package. Check out [this pull request](https://github.com/yahoo/flux-router-component/pull/81) for more info.

**Comment by daannijkamp** [comment]
Thanks! I can't wait!
