### ISSUE TITLE
Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by Vijar** [yahoo/fluxible.io#116]
Sometimes this error happens if you click around on the links too fast

![screen shot 2015-04-22 at 4 41 58 pm](https://cloud.githubusercontent.com/assets/759766/7287858/b9deb4f2-e90e-11e4-81f9-0345bcea71fb.png)

**Comment by mridgway** [comment]
The `onClick` handler needs to be bound here: https://github.com/yahoo/fluxible.io/blob/master/components/Menu.jsx#L36
