### ISSUE TITLE
Fluxible-router for fluxible.io?

### ISSUE THREAD

**Issue by jhwang09** [yahoo/fluxible.io#119]
Will we be able to see Fluxible.io to use Fluxible-router anytime soon? It'll be a great help for us to migrate to the new router.

Thanks

**Comment by redonkulus** [comment]
@jhwang09 yup @jedireza is working on it as we speak and should have something this week. We will also publish an upgrade guide to help with migrations.

**Comment by jhwang09** [comment]
awesome! thanks!
