### ISSUE TITLE
Links from AddOns pages to non-AddOns pages produce 404 errors

### ISSUE THREAD

**Issue by jeffhandley** [yahoo/fluxible.io#128]
**On this page:**
http://fluxible.io/api/addons/provideContext.html

Click the link for the "FluxibleContext.createElement() method."

**Expected:**
http://fluxible.io/api/fluxible-context.html#createelement-props-

**Actual:**
http://fluxible.io/api/FluxibleContext.md#createelement-props-
This produces a 404 error.

**Comment by jeffhandley** [comment]
This is a more general problem.  Every link from all AddOn pages that navigates to the parent directory (outside of the addons directory) produces a 404.

**Comment by jeffhandley** [comment]
It looks like this has regressed -- haven't looked at the code to see if it's the exact same issue though.  Would you prefer re-opening this issue or would you like me to file a new one?

Example:
From http://fluxible.io/api/fluxible-context.html, try clicking on the Action Context link.

Actual (404):
http://fluxible.io/api/Actions.md#action-context

Expected:
http://fluxible.io/api/Actions.html#action-context

**Comment by redonkulus** [comment]
Ya this was regressed when we split out the addons to a separate package. Must be a bug in the logic for absolute URLs. Lets open a new issue.
