### ISSUE TITLE
Server hangs when components throw errors on the server side

### ISSUE THREAD

**Issue by jhwang09** [yahoo/fluxible.io#131]
I finally realize why my server will hang unexpectedly and was not providing meaningful error messages. 

It's because whenever the components failed in the this function (below link), the express sever did not know what to do, there wasn't a "send" nor "next", thus express froze

https://github.com/yahoo/fluxible.io/blob/master/server.js#L40

It should have a try...catch to wrap the code of "renderApp" and use Express "next" to bring the error message to the next middleware (or display error on the page)

**Comment by redonkulus** [comment]
@jhwang09 which error were you seeing?  We are not handling the [error case](https://github.com/yahoo/fluxible.io/blob/master/server.js#L68), so we could fix the code to handle that better.

**Comment by jhwang09** [comment]
Hi, there is no error there. I just thought itll be helpful to have it there since most people would read fluxible.io as example for fluxilbe. I myself follow fluxible.io and have my server hangs whenever my component is throwing errors. Having a try catch there will help us better in debugging server side issue. This is merely just a suggestion so no one step into my shoes again. It took me couple weeks to actually figure out why the server hangs. 

If youre not sure what i meant, just find one component and remove one of the require component from the component and the server will hang for the request.

**Comment by redonkulus** [comment]
@jhwang09 ok, i've added the fix https://github.com/yahoo/fluxible.io/commit/11ca387d6843dcc3de6b1df5f03019b408062ad4 , hopefully this helps others later.

**Comment by jhwang09** [comment]
hmm.. this isn't what i meant..  this will catch error if the action is throwing error.

you should put try catch around the renderApp method

try {
renderApp(res, context);
}cactch(e) {
 next(e);
}

I am prevent if any react component is throwing error, not the action itself
