### ISSUE TITLE
js or jsx extension ?

### ISSUE THREAD

**Issue by LeoAJ** [yahoo/fluxible.io#134]
On page  http://fluxible.io/tutorials/routing.html

If we use `Application.js` as `js` file instead of `jsx` file

then should we set extension as `js` in node-jsx ? right ?

Attached screen shot, thanks!

https://www.evernote.com/shard/s23/sh/4901297d-2447-468f-9aba-96b7a2291c55/86cc1a564bf73893

**Comment by redonkulus** [comment]
It should probably use jsx to ensure its compiled correctly. Although, we use babel now to do the compiling and this supports either extension.

**Comment by LeoAJ** [comment]
Thanks! @redonkulus 

Any plan on updating tutorial in this page ? http://fluxible.io/tutorials/routing.html

perhaps the module update and some of example is not working now.

Thanks!

**Comment by redonkulus** [comment]
Fixed here https://github.com/yahoo/fluxible/commit/0c9bc3b99d1557c5d711226e4bb1bc86937c5083
