### ISSUE TITLE
http://fluxible.io/api/stores.html throws error

### ISSUE THREAD

**Issue by mypark** [yahoo/fluxible.io#147]
in docs - http://fluxible.io/api/stores.html throws error when I first tried to click to it from the quickstart page, but then loaded correctly when I navigated to it from the left navigation and all subsequent times.

Error
Sorry there was an unexpected errror.

Back to the home page.

**Comment by redonkulus** [comment]
@mypark I can't seem to replicate. Can you try again?

**Comment by mypark** [comment]
hmm.. seems to be working now - not sure why it didn't work before..

**Comment by mridgway** [comment]
May have been cached for you. It was broken a couple of days ago, due to doc restructuring. Let us know if you see the issue you again.
