### ISSUE TITLE
Components documentation mixes es6 style

### ISSUE THREAD

**Issue by mypark** [yahoo/fluxible.io#148]
Not sure if the example in http://fluxible.io/api/components.html, "Accessing Stores" is correct.

If I try to declare getInitialState() with the ES6 class style, I get a warning and error.

```
Warning: getInitialState was defined on SearchResults,
a plain JavaScript class. This is only supported for 
classes created using React.createClass. Did you mean 
to define a state property instead?
```

http://stackoverflow.com/questions/33510553/error-trying-to-declare-my-fluxible-react-js-component-in-an-es6-class/33510703#33510703

Is the example incorrect?

**Comment by mridgway** [comment]
Yes, you are correct. It needs to be fixed to use the constructor to set that state instead.

**Comment by redonkulus** [comment]
@mypark this is now [fixed].(https://github.com/yahoo/fluxible/commit/2479116ed6c5cc9e01309b274107184725c6d3fa)

**Comment by mypark** [comment]
I'm getting an error of undefined this.context using that sample code. Since I'm using the the yeoman fluxible template I'm assuming that context is automagically passed to child components.. Is there something else that I need to do?  It looks like the context is initially passed in via client.js in the app.rehydrate.  How do I make sure it goes to the child controls?

**Comment by redonkulus** [comment]
@mypark do you have a link to your code somewhere? Assuming you are using http://fluxible.io/addons/provideContext.html

**Comment by mypark** [comment]
Here's the code to my component.  https://gist.github.com/mypark/5eb0ff5c40f6acf39a1f

I'm using the fluxible yeoman template, and looking at that code it seems to have it's own provideContext function in components/Application.js

```
export default provideContext(handleHistory(connectToStores(
    Application,
    [ApplicationStore],
    function (context, props) {
        var appStore = context.getStore(ApplicationStore);
        return {
            pageTitle: appStore.getPageTitle()
        };
    }
)));
```

but I don't see it using the provideContext add on.

**Comment by mypark** [comment]
Maybe you can point me to an example using the fluxible starter template with the es6 style classes?

**Comment by redonkulus** [comment]
@mypark you can look at our docs site for a more detailed example of how we set it up: https://github.com/yahoo/fluxible.io

**Comment by redonkulus** [comment]
https://github.com/yahoo/flux-examples might also be of help

**Comment by mypark** [comment]
I couldn't find in any of those examples a reference to this.context in the constructor.  The context seems to exist by the time it gets to onClick event handlers but errors as null in the constructor call. Is there a point in the base component lifecycle where the context gets wired up - in which case using it in  http://fluxible.io/api/components.html  example would be incorrect?
