### ISSUE TITLE
move flickr attribution to the footer

### ISSUE THREAD

**Issue by annawchou** [yahoo/fluxible.io#39]

**Comment by jedireza** [comment]
The logo is already in the repo. We just need to put it next to the attribute line.

**Comment by kaiiu** [comment]
implement as image tag

![screen shot 2015-01-27 at 2 34 08 pm](https://cloud.githubusercontent.com/assets/5370150/5928639/98a268da-a631-11e4-8fed-5e5ccdcffcda.png)

**Comment by redonkulus** [comment]
Attribution is near the picture, closing.
