### ISSUE TITLE
Add functional tests for docs

### ISSUE THREAD

**Issue by redonkulus** [yahoo/fluxible.io#53]
Use protractor to get the based site navigation tested so we can start continuous deployment.

**Comment by cesarandreu** [comment]
Any reason why Protractor over Nightwatch.js? 

I've used Protractor in an AngularJS project, but I've heard good things about Nightwatch as well.

**Comment by redonkulus** [comment]
We've been using it internally in Yahoo for a while now and works pretty well for our needs. I personally haven't used Nightwatch.

**Comment by cesarandreu** [comment]
@redonkulus Do you guys just enable ignoreSynchronization in order to use Protractor?

**Comment by redonkulus** [comment]
@cesarandreu we did, [here](https://github.com/yahoo/fluxible.io/blob/master/tests/spec/protractor.conf.js#L12).  You can see the tests here: https://github.com/yahoo/fluxible.io/tree/master/tests/spec and run them with `grunt func`.
