### ISSUE TITLE
Add "Edit on Github" link to pages

### ISSUE THREAD

**Issue by redonkulus** [yahoo/fluxible.io#67]
We want to promote users contributing/fixing our docs. We should promote that from the site.

**Comment by jedireza** [comment]
I like how React links right to the page. You could even edit it online.

![screen shot 2015-02-05 at 10 06 46 am](https://cloud.githubusercontent.com/assets/979929/6066075/0734941e-ad1f-11e4-9b0f-2e96954f6ec8.png)

**Comment by redonkulus** [comment]
Yes, that please.
